# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zulfiqar's github home
email: zulfiqar@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zamd.net" # the base hostname & protocol for your site
twitter_username: zahmed
github_username:  zamd

# Build settings
markdown: kramdown
